theme: jekyll-theme-architect
title: K-Sudoku
description: Beautiful Sudoku puzzling
show_downloads: true
google_analytics: UA-151160883-1
github:
  contributor_url: https://github.com/milospanasiuk
  contributor_name: milospanasiuk
  linux_x64: https://github.com/ksokolovic/k-sudoku/releases/download/v1.3.0/Sudoku-linux-1.3.0-x64.tar.gz
  linux_x32: https://github.com/ksokolovic/k-sudoku/releases/download/v1.3.0/Sudoku-linux-1.3.0-ia32.tar.gz
  snap_store: https://snapcraft.io/k-sudoku
  windows_x64: https://github.com/ksokolovic/k-sudoku/releases/download/v1.3.0/Sudoku-win32-1.3.0-x64.tar.gz
  windows_x32: https://github.com/ksokolovic/k-sudoku/releases/download/v1.3.0/Sudoku-win32-1.3.0-ia32.tar.gz
  darwin: https://github.com/ksokolovic/k-sudoku/releases/download/v1.3.0/Sudoku-darwin-1.3.0-x64.tar.gz
